---
# ---- for bind server ---
#hostname の指定がない時は targetで既に設定されているhostnameを使用
hostname: subdns
#domain
resolv_domain: 
  - domain: sub.main.co.jp

# reverse_domain: x.x.x.in-addr.arpa. の記述 (zone毎にリストで記載)
# 指定がない時は、設定されている NICの subnetを用いて設定する
resolv_reverse_domain:
  - reverse_domain: 1.168.192.in-addr.arpa.
  - reverse_domain: 1.31.172.in-addr.arpa.

# record: 正引き用の DNS Record. 指定がない場合は、設定SKIP
# key/type/value は必須パラメータ
record:
  - key: test1
    type: A
    value: 192.168.1.110
  - key: test2.test
    type: A
    value: 172.31.1.100
  - key: test3
    type: CNAME
    value: test4.test3.test2.test1

# reverse_record: 逆引き用の DNS Record. 指定がない場合は、設定SKIP
# key/type/value は必須パラメータ
reverse_record:
  - key: 110
    type: PTR
    value: test1.sub.main.co.jp.
  - key: 100
    type: PTR
    value: test2.test.sub.main.co.jp.